### ISSUE TITLE
Error while Create/Refresh reporting views on webapp

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-server#280]
**Describe the bug**/**To Reproduce**
On web app, try using the "create/refresh views" in Reporting views, the reporting views are not refreshed nor created.

**Expected behaviour**
Ideally, using the "Create/Refresh" button, new reporting views should be generated or existing ones should get refreshed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Developer Checklist**
Developer fixing the bug should fill this checklist.
- [ ] Does the fix require extensive regression testing?
- [ ] Are you mentioning the required scenarios that could be affected?

**Comment by vinayvenu** [comment]
Issues fixed. 

1. Empty forms break
2. General encounter form sql is not generated correctly.

**Comment by vinayvenu** [comment]
@petmongrels can you take a look? 

```
java.lang.NullPointerException: null
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.openchs.service.ViewNameGenerator.buildProperViewName(ViewNameGenerator.java:33)
	at org.openchs.service.ViewNameGenerator.getViewName(ViewNameGenerator.java:66)
	at org.openchs.service.ViewNameGenerator.getProgramEncounterViewName(ViewNameGenerator.java:46)
	at org.openchs.visitor.GetReportingViewSourceVisitor.visit(GetReportingViewSourceVisitor.java:66)
	at org.openchs.domain.metadata.SubjectTypes.lambda$null$0(SubjectTypes.java:29)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.openchs.domain.metadata.SubjectTypes.lambda$null$1(SubjectTypes.java:28)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.openchs.domain.metadata.SubjectTypes.lambda$accept$2(SubjectTypes.java:27)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.openchs.domain.metadata.SubjectTypes.accept(SubjectTypes.java:26)
	at org.openchs.web.ViewGenController.createViews(ViewGenController.java:71)
	at org.openchs.web.ViewGenController$$FastClassBySpringCGLIB$$8d3e4659.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.openchs.web.ViewGenController$$EnhancerBySpringCGLIB$$206a68ff.createViews(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Met
```

**Comment by nupoorkhandelwal** [comment]
@petmongrels On staging , i am still getting this error on "Refresh/Create Views"--

![Screenshot from 2021-02-26 10-06-22.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/2455fad4-209e-44c3-913c-cf9c20bbe3a8)

**Comment by nupoorkhandelwal** [comment]
Solution involves two steps:
1. try changing schema name from db to not to contain '-'
2. go to UI and simply press update org without any change (it would create schema with changed name)
