### ISSUE TITLE
NullPointer on /web/message/user/[id]/msgsNotYetSent after scheduling a message

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-server#517]
Schedule a message to a user for a future time.
Refresh page to retrieve messages for the user.
/msgsNotYetSent throws an error till the message is sent to the user.

```
2023-03-16 11:55:58.591 ERROR 10288 --- [http-nio-8021-exec-3] org.avni.server.web.ErrorInterceptors    : null

java.lang.NullPointerException: null
	at org.avni.messaging.contract.web.MessageRequestResponse.fromMessageRequest(MessageRequestResponse.java:25)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.avni.messaging.api.MessageController.fetchAllMsgsNotYetSentForContactUser(MessageController.java:56)

```

**Comment by 1t5j0y** [comment]
Unable to simulate any more. No change made. Moving to ready for QA for someone else to try simulating once.
