### ISSUE TITLE
Bugsnag error - glific integration error - too many events

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#574]
java.lang.NullPointerException
        at org.avni.messaging.repository.GlificMessageRepository.arrayToString(GlificMessageRepository.java:36)
        at org.avni.messaging.repository.GlificMessageRepository.sendMessageToContact(GlificMessageRepository.java:22)
        at org.avni.messaging.repository.GlificMessageRepository$$FastClassBySpringCGLIB$$2dad3d0f.invoke(<generated>:-1)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.avni.messaging.repository.GlificMessageRepository$$EnhancerBySpringCGLIB$$5955bd8b.sendMessageToContact(<generated>:-1)
        at org.avni.messaging.service.IndividualMessagingService.ensureExternalIdPresenceAndSendMessage(IndividualMessagingService.java:42)
        at org.avni.messaging.service.IndividualMessagingService.sendAutomatedMessage(IndividualMessagingService.java:49)
        at org.avni.messaging.service.MessagingService.sendMessageToGlific(MessagingService.java:158)
        at org.avni.messaging.service.MessagingService.sendMessage(MessagingService.java:118)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at org.avni.messaging.service.MessagingService.sendMessages(MessagingService.java:141)
        at org.avni.messaging.service.MessagingService$$FastClassBySpringCGLIB$$a16061e8.invoke(<generated>:-1)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.avni.messaging.service.MessagingService$$EnhancerBySpringCGLIB$$d4f916e9.sendMessages(<generated>:-1)
        at org.avni.messaging.service.MessageSenderJob.sendMessages(MessageSenderJob.java:56)
        at org.avni.messaging.service.MessageSenderJob.sendMessages(MessageSenderJob.java:46)
        at sun.reflect.GeneratedMethodAccessor1940.invoke(Unknown:-1)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/6452514765a32f000861e8d7

**Comment by petmongrels** [comment]
duplicate
