### ISSUE TITLE
Error during creation of entities from Integration-service using Avni External APIs

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-server#604]
## Bugsnag Error:

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/65018d5444463d000822f6e8

## Details

While trying to sync Implementation Inventory from Salesforce to Avni, we are encountering following error:

### Request Payload to create Implementation Inventory Subject
```
{
  "Subject type": "Inventory Item",
  "Address": "Kerala, Alappuzha",
  "Registration date": "2023-09-15",
  "observations": {
    "Initial Quantity": 100.0,
    "Center / Field office": "Goonj",
    "Dispatch Line Item Id": null,
    "Purchased/ Created/ Received": "Received",
    "Purchase Kit name": null,
    "Bill name": null,
    "Other material name": null,
    "Kit Type": "CFW",
    "Unit": "Nos",
    "Dispatch Status Id": "a1A72000000bIFhEAM",
    "Dispatch Received Date": "2023-08-24",
    "Dispatch Received Status Line Item Id": "a2472000002Xk9NAAS",
    "Material sub category": null,
    "Dispatch Status Name": "2023/RAJ/ACC-195025/KER/044",
    "Material Name": "ACC-195088-GK-CFW(A)-7",
    "Account  name": "FO1",
    "Sub type": "A",
    "Current Quantity": 39.0,
    "Type Of Material": "Kit",
    "Vehicle type": null,
    "Material type": null
  },
  "First name": "CFW A-2023/RAJ/ACC-195025/KER/044-100",
  "Voided": false,
  "External ID": "a2972000000RJmXAAW"
}
```

### Logs
2023-09-14 10:04:14.606 ERROR 18307 --- [http-nio-8021-exec-793] org.avni.server.web.ErrorInterceptors    : failed to lazily initialize a collection of role: org.avni.server.domain.Individual.relationshipsFromSelfToOthers, could not initialize proxy - no Session

org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.avni.server.domain.Individual.relationshipsFromSelfToOthers, could not initialize proxy - no Session
        at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:582)
        at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:201)
        at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:561)
        at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:132)
        at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:163)
        at java.lang.Iterable.forEach(Iterable.java:74)
        at org.avni.server.web.response.SubjectResponse.putRelatives(SubjectResponse.java:58)
        at org.avni.server.web.response.SubjectResponse.fromSubject(SubjectResponse.java:31)
        at org.avni.server.web.api.SubjectApiController.updateSubjectAndSave(SubjectApiController.java:127)
        at org.avni.server.web.api.SubjectApiController.post(SubjectApiController.java:116)
        at org.avni.server.web.api.SubjectApiController$$FastClassBySpringCGLIB$$399870af.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.avni.server.web.api.SubjectApiController$$EnhancerBySpringCGLIB$$1fa1dda.post(<generated>)
        at sun.reflect.GeneratedMethodAccessor1224.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.avni.server.framework.sync.MutableRequestFilter.doFilter(MutableRequestFilter.java:20)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

**Comment by himeshr** [comment]
In-order to reproduce this issues, performed testing on multiple environments.
The issue was encountered only during update of an existing Individual, when the update request had changes in
1. any of the SyncConcept related attributes OR
2. Address attribute

To fix this, we'll make use of individualRepository.save() response value to perform any further operations during upsert of an Individual.

**Comment by himeshr** [comment]
For QA, validate "POST" method for all Avni Core Entity types:
1. Subject
2. Encounter
3. ProgramEncounter
4. ProgramEnrolment
5. Task
