### ISSUE TITLE
After login sync got failed

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-server#621]
Steps to reproduce:
1.Login to app 
2.enter the user and password and login 
Excpeted result : user got synced and displayed with the home page
Actual Result : user get the sync failled error code : 500

Env : prod 
Version : 5.0.0-617a
user : AchalaB@sncu 
user : AchalaB@shelteruat

<img width="569" alt="Screenshot 2023-10-05 at 5 01 02 PM" src="https://github.com/avniproject/avni-client/assets/127730126/b7c4de1d-bc5c-4aa8-b5e4-d6b2fc87ece8">

## Analysis details:
not happening on 4.01.0
server stack trace:
```
2023-10-05 11:58:39.244 ERROR 25004 --- [http-nio-8021-exec-25] org.avni.server.util.BugsnagReporter     : No enum constant org.avni.server.dao.sync.SyncEntityName.VideoTelemetric

java.lang.IllegalArgumentException: No enum constant org.avni.server.dao.sync.SyncEntityName.VideoTelemetric
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.avni.server.dao.sync.SyncEntityName.valueOf(SyncEntityName.java:9)
	at org.avni.server.web.SyncController.filterChangedEntities(SyncController.java:392)
	at org.avni.server.web.SyncController.lambda$getChangedEntities$2(SyncController.java:348)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.avni.server.web.SyncController.getChangedEntities(SyncController.java:349)
	at org.avni.server.web.SyncController.getSyncDetailsWithScopeAwareEAS(SyncController.java:306)
	at org.avni.server.web.SyncController$$FastClassBySpringCGLIB$$cb0b7ba8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

```

**Comment by petmongrels** [comment]
### about changes
- most avni-client changes are made to master
- model version upgrade commit and avn-models changes to 5.0
- avni-server change is to allow for older versions of mobile app as they were also facing problem, so it is needed for some time.
