### ISSUE TITLE
Msg91 send OTP javax.crypto.AEADBadTagException

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-server#673]
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/6585530be11f9c00080046df

```
javax.crypto.AEADBadTagException: Tag mismatch!
        at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:620)
        at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
        at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at javax.crypto.Cipher.doFinal(Cipher.java:2168)
        at org.avni.server.service.CryptoService.decrypt(CryptoService.java:57)
        at org.avni.server.service.CryptoService.decryptWithIVPrefixed(CryptoService.java:67)
        at org.avni.server.service.Msg91ConfigService.decryptAuthKey(Msg91ConfigService.java:28)
        at org.avni.server.service.PhoneNumberVerificationService.createMsg91Request(PhoneNumberVerificationService.java:186)
        at org.avni.server.service.PhoneNumberVerificationService.sendOTP(PhoneNumberVerificationService.java:56)
        at org.avni.server.web.PhoneNumberVerificationController.sendOTP(PhoneNumberVerificationController.java:36)
        at org.avni.server.web.PhoneNumberVerificationController$$FastClassBySpringCGLIB$$12fce09d.invoke(<generated>:-1)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
```

**Comment by 1t5j0y** [comment]
Root cause: Incorrect encryption key configured for prod environment.
