### ISSUE TITLE
Server communication error on editing catchment of a user

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/avni-server#819]
https://avni.freshdesk.com/a/tickets/4984

**Describe the bug**
On editing catchment of the user, we get a toast saying "Sever communication error" and it doesn't all the user to edit and save.

**Steps to reproduce** 
1. Remove grant select for a db user
(We fixed it by running the following script - `grant select on account to shelteruat;`)

**Logs from server**
```
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)....

Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for table account
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)......

2024-11-12 10:15:06.042 ERROR 2500080 --- [http-nio-8021-exec-301] org.avni.server.util.BugsnagReporter     : could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:242)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225).......
```

**Comment by petmongrels** [comment]
### Hypothesis
- we should check when we provision a new organisation whether that org db user gets select access to account table
- technically the org user should not have this access but because of hibernate OR mapping we cannot control what is loaded by the object dependency graph

### fix
- we should fix all the existing organisation db user's access

**Comment by mahalakshme** [comment]
@Gojo-Taqi / @petmongrels kindly add how to reproduce the issue. It is not clear.
happens always? which org? which catchment?

**Comment by 1t5j0y** [comment]
Since this error causes a privilege escalation in effect as seen in #824, we should probably block this at the auth level itself.

**Comment by himeshr** [comment]
- Confirmed that as part of New Org creation in Avni, we do invoke "create_db_user" with configured db_user role.
- Fix to resolve the dbRole access issues already present for all openchs tables will be done by executing https://github.com/avniproject/data-fixes/blob/main/all/recreate_db_user.sql

**Comment by petmongrels** [comment]
if someone else picks up. lets pair.
